name: Push to TheFluxTrain public Replicate
 
on:
  push:
    branches:
      - fluxtrain
 
jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk pace
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false
 
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN_THEFLUXTRAIN }}
        
      - name: Push to Replicate
        run: cog push r8.im/thefluxtrain/oye-cartoon